title: "Gitansh Vachher"
description: "Trying to figure out what happens to delivery work when delivery people stop being afraid of the code."
author: "Gitansh Vachher"
theme: minima
permalink: /writing/:slug/
include:
  - assets
