title: "Gitansh Vachher"
description: "Experimenting with AI to collapse busywork. Sharing what I learn in public."
author: "Gitansh Vachher"
theme: minima
twitter_username: gitansh_vachher
# Minima adds a header automatically; we’ll hide it with CSS to keep the page ultra-minimal.
